### PR TITLE
Slash Commands For Pogy

### PR DESCRIPTION
**Pull request by eYuM-coder**
Here is my attempt at slash commands for Pogy. The code may be a little sloppy but I'm working on it!

### CODE REVIEW

**Comment by Boeing-737-800** [comment]
Things that were added/modified:
- index.js and Pogy.js had to be modified for slash command support.
- config.json.template has been modified for deployCommands.js, which can be found in the src folder.
- deployCommands.js, mute.js, and unmute.js are new files that have been added, mute.js and unmute.js can be found in the slashCommands folder.

**Comment by Boeing-737-800** [comment]
Note: Some commits on this PR ARE NOT made by me, they are old commits that GitHub keeps pushing to every PR I make on a personal computer I use. This may be an issue with GitHub and VSCode not having compatibility with each other on personal computers. Just letting reviewers know.

**Comment by eYuM-coder** [comment]
Even though I am importing slash commands to this repository, I also decided to import a new category as well

**Comment by DuckoDas** [comment]
Bro was bored af

**Comment by livingfaraway** [comment]
bro how bored are u

**Comment by thealzhe** [comment]
Any official PR / release?

**Comment by peterhanania** [comment]
This has been moved to a new branch #34

**Pull request closed without merging**
