### PR TITLE
Add hack.js command back

### PR DESCRIPTION
**Pull request by Boeing-737-800**
Bugs were fixed and added some improvements to code

### CODE REVIEW

**Review by fb-sean — COMMENTED** [review]
Need a fix

**Comment by Boeing-737-800** [comment]
Arrays do not work with this command.

**Comment by fb-sean** [comment]
Updated version of this command without 10k timeouts also with some required checks. 

=> https://sourceb.in/uwerCOLDMp

**Comment by XstreamSpeed** [comment]
> Need a fix

Damn what are you doing here

**Pull request closed without merging**
